name: Convert DOCX to Markdown  # Updated name to reflect new purpose

on:
  push:
    paths:
      - "docs/IncomingDocs/*.docx"  # Workflow triggers when a DOCX file changes
  workflow_dispatch:  # Allows manual triggering

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: ./.github/actions/checkout

      
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
      
      - name: Convert DOCX to Markdown
        run: |
          mkdir -p docs/ImportDocs/markdown  # Create markdown directory if it doesn't exist
          for file in docs/IncomingDocs/*.docx; do  # Loop through all DOCX files
            if [ -f "$file" ]; then  # Check if file exists
              filename=$(basename "$file")  # Get filename without path
              pandoc "$file" -f docx -t markdown -o "docs/ImportDocs/markdown/${filename%.docx}.md"  # Convert DOCX to MD
            fi
          done

      - name: Commit generated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/ImportDocs/markdown/*.md  # Add generated markdown files
          git commit -m "Auto-generate Markdown from DOCX files" || echo "No changes to commit"
          git push
