name: Convert Markdown to DOCX & PDF

on:
  push:
    paths:
      - "docs/ImportDocs/markdown/*.md"
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install Pandoc & Full LaTeX
        run: sudo apt-get install -y pandoc texlive texlive-xetex texlive-fonts-recommended texlive-latex-extra
      
      - name: Install extra fonts
        run: sudo apt-get install -y fonts-dejavu fonts-lmodern

      - name: Convert Markdown to DOCX
        run: |
          mkdir -p docs/ImportDocs/docx
          for file in docs/ImportDocs/markdown/*.md; do
            pandoc "$file" -o "docs/ImportDocs/docx/$(basename "${file%.md}.docx")"
          done

      - name: Convert Markdown to PDF
        run: |
          mkdir -p docs/ImportDocs/pdf
          for file in docs/ImportDocs/markdown/*.md; do
            pandoc "$file" --pdf-engine=pdflatex -o "docs/ImportDocs/pdf/$(basename "${file%.md}.pdf")"
          done

      - name: Commit generated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/ImportDocs/docx/*.docx docs/ImportDocs/pdf/*.pdf
          git commit -m "Auto-generate DOCX & PDF from Markdown" || echo "No changes to commit"
          git push
